PERSPECTIVE_API_KEY = "AIzaSyCDLFHm1zNjKwsaP8oVhWC8ylswhNM6nnM"
OPENAI_API_KEY = "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"
